pipeline {
    agent any
/*     environment {
      PATH = "${PATH}:${getTerraformPath()}"
    } */
    stages {
        stage('Initialize production'){
            steps {
                echo "hello world"
            }
        }
    }
}

/*
def getTerraformPath(){
    def tfHome = tool name: 'terraform-12', type: 'terraform'
    return tfHome
} */
