AWSTemplateFormatVersion: 2010-09-09
Mappings:
  RegionMap:
    us-east-1:
      AMI: "ami-0d5eff06f840b45e9"
      TestAz: "us-east-1a"
    us-west-1:
      AMI: "ami-04468e03c37242e1e"
      TestAz: "us-west-1a"
    us-west-2:
      AMI: "ami-0cf6f5c8a62fa5da6"
      TestAz: "us-west-2a"
    eu-west-1:
      AMI: "ami-0cf6f5c8a62fa5da6"
      TestAz: "eu-west-1a"
    ap-southeast-1:
      AMI: "ami-02f26adf094f51167"
      TestAz: "ap-southeast-1a"
    ap-southeast-2:
      AMI: "ami-0186908e2fdeea8f3"
      TestAz: "ap-southeast-2a"
    ap-northeast-1:
      AMI: "ami-0ca38c7440de1749a"
      TestAz: "ap-northeast-1"

Parameters:
  EnvType:
    Description: 'Environment Type'
    Default: 'test'
    Type: String
    AllowedValues:
      - prod
      - test
    ConstraintDescription: 'must specify prod or test'

Conditions:
  CreateProdResources: !Equals [ !Ref EnvType, prod ]

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [ RegionMap, !Ref "AWS::Region", AMI ]
      InstanceType: t2.micro

  # If the environment is "PROD", then create and mount a Volume.
  # This is a condition.
  MountPoint:
    Type: AWS::EC2::VolumeAttachment
    Condition: CreateProdResources
    Properties:
      InstanceId: !Ref EC2Instance
      VolumeId: !Ref NewVolume
      Device: /dev/sdh

  NewVolume:
    Type: AWS::EC2::Volume
    Condition: CreateProdResources
    Properties:
      Size: 100
      AvailabilityZone: !GetAtt EC2Instance.AvailabilityZone

Outputs:
  VolumeId:
    Condition: CreateProdResources
    Value: !Ref NewVolume