AWSTemplateFormatVersion: 2010-09-09

Resources:
  MySecurityInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0d5eff06f840b45e9
      InstanceType: t2.micro
      SecurityGroups:
        # we reference the output, using the Fn::ImportValue function
        - !ImportValue SSHSecurityGroup